export enum NotificationTitleEnum {
  SUCCESS = 'SHARED.NOTIFICATION.SUCCESS',
  INFODEV = 'SHARED.NOTIFICATION.INFO-FOR-DEVELOPER',
  ERROR = 'SHARED.NOTIFICATION.ERROR',
  ATTENTION = 'SHARED.NOTIFICATION.ATTENTION'
}

export enum NotificationDelayEnum {
  FIVE = 5000,
  TEN = 10000,
  FIFTEEN = 15000
}
